// Design-space dimensions for every strip (2in x 6in ratio = 1:3).
// All slot / decoration coordinates below are in this space and get scaled at render time.
export const STRIP_W = 300;
export const STRIP_H = 900;

const S = "/stickers/";
const SHIN = S + "shinchan/";
const KAWAII = S + "pink-kawaii/";
const BLUE_KAWAII = S + "blue-kawaii/";
const YELLOW_KAWAII = S + "yellow-kawaii/";

const SHINCHAN_STICKERS = [
  SHIN + "shin-top.png",
  SHIN + "shiro-top.png",
  SHIN + "action-mask-center.png",
  SHIN + "blue-hair-top.png",
  SHIN + "boar-top.png",
  SHIN + "croc-top.png",
  SHIN + "curly-center.png",
  SHIN + "friend-left.png",
  SHIN + "mint-smile-top.png",
  SHIN + "nene-top.png",
];

const PINK_KAWAII_STICKERS = [
  KAWAII + "cake-nap-left.png",
  KAWAII + "cake-party-left.png",
  KAWAII + "dessert-platter-left.png",
  KAWAII + "fruit-bowl-left.png",
  KAWAII + "giant-jelly-left.png",
  KAWAII + "cake-stand-left.png",
  KAWAII + "cake-slice-left.png",
  KAWAII + "pudding-cuddle-left.png",
  KAWAII + "pudding-hug-left.png",
  KAWAII + "strawberry-drink-left.png",
  KAWAII + "rolled-cake-plate.png",
  KAWAII + "pudding-trio.png",
  KAWAII + "bear-face-left.png",
];

const BLUE_KAWAII_STICKERS = [
  BLUE_KAWAII + "fish-friend.png",
  BLUE_KAWAII + "mermaid-bear.png",
  BLUE_KAWAII + "sleepy-bear.png",
  BLUE_KAWAII + "coral-nap.png",
  BLUE_KAWAII + "round-fish.png",
  BLUE_KAWAII + "jellyfish.png",
  BLUE_KAWAII + "submarine.png",
  BLUE_KAWAII + "otter-bear.png",
  BLUE_KAWAII + "shell-bed.png",
  BLUE_KAWAII + "starfish.png",
  BLUE_KAWAII + "star-hug.png",
  BLUE_KAWAII + "treasure-box.png",
  BLUE_KAWAII + "tiny-fish.png",
  BLUE_KAWAII + "seaweed.png",
  BLUE_KAWAII + "swimming-bear.png",
  BLUE_KAWAII + "moon-bubble.png",
  BLUE_KAWAII + "purple-shell.png",
  BLUE_KAWAII + "coral-shell.png",
];

const YELLOW_KAWAII_STICKERS = [
  YELLOW_KAWAII + "blue-scarf.png",
  YELLOW_KAWAII + "pink-camera.png",
  YELLOW_KAWAII + "sitting-cat.png",
  YELLOW_KAWAII + "picnic-basket.png",
  YELLOW_KAWAII + "campfire-snack.png",
  YELLOW_KAWAII + "snack-time.png",
  YELLOW_KAWAII + "pink-cup.png",
  YELLOW_KAWAII + "camp-sign.png",
  YELLOW_KAWAII + "tent-camp.png",
  YELLOW_KAWAII + "flag-cat.png",
  YELLOW_KAWAII + "photo-cards.png",
  YELLOW_KAWAII + "winter-hug.png",
  YELLOW_KAWAII + "green-tree.png",
  YELLOW_KAWAII + "instrument-cat.png",
  YELLOW_KAWAII + "fish-hug.png",
];

// 3-photo slot layout
const SLOTS_3 = [
  { x: 26, y: 64, w: 248, h: 185 },
  { x: 26, y: 277, w: 248, h: 185 },
  { x: 26, y: 490, w: 248, h: 185 },
];

// 4-photo slot layout
const SLOTS_4 = [
  { x: 26, y: 52, w: 248, h: 160 },
  { x: 26, y: 228, w: 248, h: 160 },
  { x: 26, y: 404, w: 248, h: 160 },
  { x: 26, y: 580, w: 248, h: 160 },
];

export const TEMPLATES = [
  {
    id: "cherry-red",
    name: "Cherry Red",
    cta: "Pick Cherry 🍒",
    accent: "#8a2b2b",
    bg: { type: "gingham", color: "#a23030", base: "#fbeee9", cell: 9 },
    panel: { x: 16, y: 52, w: 268, h: 636, r: 16, color: "#7d1b1b", dots: "#f4e3d8", dotCell: 20 },
    matColor: "#ffffff",
    photoBorder: "#ffffff",
    slots: SLOTS_3,
    decorations: [
      { src: S + "satin-bow.png", x: 150, y: 36, size: 72 },
      { src: S + "hibiscus.png", x: 44, y: 60, size: 52, rot: -0.25 },
      { src: S + "cherries.png", x: 252, y: 262, size: 76, rot: 0.12 },
      { src: S + "hibiscus.png", x: 250, y: 660, size: 50, rot: 0.2 },
      { src: S + "gingham-bow.png", x: 150, y: 702, size: 86 },
    ],
    palette: [
      S + "satin-bow.png",
      S + "gingham-bow.png",
      S + "hibiscus.png",
      S + "cherries.png",
      S + "swirl-red.svg",
      S + "cherry.svg",
    ],
    title: { text: "Cherry", x: 150, y: 762, size: 46, color: "#8a2b2b", font: '"Dancing Script", cursive', weight: "700" },
  },
  {
    id: "pink-sweetie",
    name: "Sweetie",
    cta: "Choose Sweetie 🎀",
    accent: "#e06ea0",
    bg: { type: "stripes", color: "#fad3e4", base: "#fff4f9", cell: 12 },
    panel: { x: 16, y: 40, w: 268, h: 712, r: 18, color: "#fbe2ee", dots: null },
    matColor: "#ffffff",
    photoBorder: "#f4bdd6",
    slots: SLOTS_4,
    decorations: [
      { src: S + "pinkclip.png", x: 150, y: 30, size: 46 },
      { src: S + "star.png", x: 256, y: 66, size: 40, rot: 0.15 },
      { src: S + "pinkflower.png", x: 44, y: 214, size: 50, rot: -0.15 },
      { src: S + "star.png", x: 256, y: 248, size: 30, rot: -0.1 },
      { src: S + "pinkcamera.png", x: 255, y: 392, size: 58, rot: 0.1 },
      { src: S + "pinkstamp.png", x: 46, y: 572, size: 46, rot: -0.1 },
      { src: S + "button.png", x: 58, y: 662, size: 30 },
      { src: S + "pinkbow.png", x: 150, y: 770, size: 80 },
    ],
    palette: [
      S + "pinkbow.png",
      S + "pinkclip.png",
      S + "pinkflower.png",
      S + "pinkstamp.png",
      S + "pinkcamera.png",
      S + "star.png",
      S + "button.png",
    ],
    title: { text: "Sweetie", x: 150, y: 816, size: 40, color: "#e06ea0", font: '"Dancing Script", cursive', weight: "700" },
  },
  {
    id: "matcha",
    name: "Matcha",
    cta: "Sip Matcha 🍵",
    accent: "#5f8a3a",
    bg: { type: "polka", base: "#bcd89a", dot: "#ffffff", cell: 26 },
    matColor: "#ffffff",
    photoBorder: "#a7cd7d",
    slots: SLOTS_3,
    decorations: [
      { src: S + "matcha-blossom.png", x: 46, y: 58, size: 48, rot: -0.15 },
      { src: S + "matcha-whisk.png", x: 256, y: 62, size: 46, rot: 0.2 },
      { src: S + "matcha-flowers.png", x: 44, y: 262, size: 44 },
      { src: S + "matcha-cup.png", x: 260, y: 272, size: 40, rot: 0.05 },
      { src: S + "matcha-strawberry.png", x: 46, y: 478, size: 42, rot: -0.1 },
      { src: S + "matcha-iced.png", x: 258, y: 486, size: 42 },
      { src: S + "matcha-mug.png", x: 150, y: 712, size: 64 },
    ],
    palette: [
      S + "matcha-mug.png",
      S + "matcha-cup.png",
      S + "matcha-iced.png",
      S + "matcha-whisk.png",
      S + "matcha-blossom.png",
      S + "matcha-flowers.png",
      S + "matcha-strawberry.png",
    ],
    title: { text: "Matcha", x: 150, y: 808, size: 40, color: "#4f7d2f", font: '"Dancing Script", cursive', weight: "700" },
  },
  {
    id: "shinchan",
    name: "Shinchan",
    cta: "Pick Shinchan ⭐",
    accent: "#35a8e8",
    bg: { type: "vstripes", color: "#51b8ed", base: "#83d1f4", cell: 11 },
    panel: { x: 15, y: 42, w: 270, h: 706, r: 5, color: "#f5b5d0", dots: null },
    matColor: "#fff9fc",
    photoBorder: "#39a9dc",
    slots: [
      { x: 35, y: 72, w: 230, h: 180 },
      { x: 35, y: 280, w: 230, h: 180 },
      { x: 35, y: 488, w: 230, h: 180 },
    ],
    decorations: [
      { src: SHIN + "action-mask-center.png", x: 62, y: 64, size: 48, rot: -0.12 },
      { src: SHIN + "blue-hair-top.png", x: 244, y: 65, size: 51, rot: 0.08 },
      { src: SHIN + "boar-top.png", x: 28, y: 253, size: 42, rot: -0.18 },
      { src: SHIN + "croc-center.png", x: 270, y: 270, size: 50, rot: 0.13 },
      { src: SHIN + "mint-smile-left.png", x: 29, y: 461, size: 47, rot: -0.08 },
      { src: SHIN + "curly-center.png", x: 269, y: 473, size: 47, rot: 0.12 },
      { src: SHIN + "nene-bottom.png", x: 43, y: 682, size: 54, rot: -0.08 },
      { src: SHIN + "shiro-top.png", x: 253, y: 683, size: 58, rot: 0.08 },
      { src: SHIN + "shin-top.png", x: 86, y: 747, size: 60, rot: -0.05 },
      { src: SHIN + "friend-left.png", x: 218, y: 746, size: 55, rot: 0.06 },
    ],
    palette: SHINCHAN_STICKERS,
    title: {
      text: "Shinchan",
      x: 150,
      y: 821,
      size: 30,
      color: "#1698d2",
      font: '"Quicksand", sans-serif',
      weight: "700",
    },
  },
  {
    id: "pink-kawaii",
    name: "Pink Kawaii",
    cta: "Pick Pink Kawaii 🧁",
    accent: "#ee91b4",
    bg: { type: "grid", color: "#eaa0bb", base: "#fff5f8", cell: 14 },
    panel: { x: 14, y: 34, w: 272, h: 724, r: 4, color: "#f9c7d9", dots: null },
    matColor: "#fffdfd",
    photoBorder: "#82bde8",
    slots: [
      { x: 35, y: 58, w: 230, h: 143 },
      { x: 35, y: 228, w: 230, h: 143 },
      { x: 35, y: 398, w: 230, h: 143 },
      { x: 35, y: 568, w: 230, h: 143 },
    ],
    decorations: [
      { src: KAWAII + "cake-nap-left.png", x: 69, y: 46, size: 61, rot: -0.08 },
      { src: KAWAII + "pudding-trio.png", x: 243, y: 49, size: 52, rot: 0.08 },
      { src: KAWAII + "pudding-hug-left.png", x: 27, y: 210, size: 51, rot: -0.1 },
      { src: KAWAII + "cake-slice-right.png", x: 272, y: 216, size: 50, rot: 0.1 },
      { src: KAWAII + "bear-face-left.png", x: 86, y: 210, size: 32, rot: -0.08 },
      { src: KAWAII + "cake-stand-right.png", x: 215, y: 211, size: 37, rot: 0.05 },
      { src: KAWAII + "strawberry-drink-left.png", x: 27, y: 382, size: 48, rot: -0.08 },
      { src: KAWAII + "rolled-cake-plate.png", x: 273, y: 386, size: 50, rot: 0.08 },
      { src: KAWAII + "pudding-trio.png", x: 82, y: 381, size: 35, rot: -0.04 },
      { src: KAWAII + "bear-face-right.png", x: 221, y: 381, size: 32, rot: 0.07 },
      { src: KAWAII + "bear-face-left.png", x: 29, y: 551, size: 43, rot: -0.08 },
      { src: KAWAII + "pudding-cuddle-right.png", x: 272, y: 555, size: 48, rot: 0.08 },
      { src: KAWAII + "cake-slice-left.png", x: 84, y: 551, size: 37, rot: -0.05 },
      { src: KAWAII + "pudding-hug-right.png", x: 219, y: 551, size: 39, rot: 0.05 },
      { src: KAWAII + "giant-jelly-left.png", x: 73, y: 727, size: 70, rot: -0.05 },
      { src: KAWAII + "dessert-platter-right.png", x: 231, y: 730, size: 68, rot: 0.05 },
      { src: KAWAII + "cake-party-left.png", x: 151, y: 726, size: 72, rot: 0 },
      { src: KAWAII + "pudding-cuddle-left.png", x: 27, y: 751, size: 42, rot: -0.12 },
      { src: KAWAII + "cake-nap-right.png", x: 275, y: 753, size: 48, rot: 0.1 },
    ],
    palette: PINK_KAWAII_STICKERS,
  },
  {
    id: "blue-kawaii",
    name: "Blue Kawaii",
    cta: "Pick Blue Kawaii 🐳",
    accent: "#6aaee8",
    bg: { type: "grid", color: "#78afe0", base: "#f3f9ff", cell: 14 },
    panel: { x: 14, y: 34, w: 272, h: 724, r: 4, color: "#b9ddf7", dots: null },
    matColor: "#fffefe",
    photoBorder: "#72b4e8",
    slots: [
      { x: 35, y: 58, w: 230, h: 143 },
      { x: 35, y: 228, w: 230, h: 143 },
      { x: 35, y: 398, w: 230, h: 143 },
      { x: 35, y: 568, w: 230, h: 143 },
    ],
    decorations: [
      { src: BLUE_KAWAII + "fish-friend.png", x: 66, y: 47, size: 62, rot: -0.08 },
      { src: BLUE_KAWAII + "mermaid-bear.png", x: 238, y: 48, size: 57, rot: 0.08 },
      { src: BLUE_KAWAII + "tiny-fish.png", x: 28, y: 129, size: 37, rot: -0.12 },
      { src: BLUE_KAWAII + "seaweed.png", x: 274, y: 137, size: 37, rot: 0.1 },
      { src: BLUE_KAWAII + "sleepy-bear.png", x: 30, y: 211, size: 52, rot: -0.08 },
      { src: BLUE_KAWAII + "round-fish.png", x: 272, y: 213, size: 46, rot: 0.08 },
      { src: BLUE_KAWAII + "jellyfish.png", x: 84, y: 211, size: 35, rot: -0.04 },
      { src: BLUE_KAWAII + "purple-shell.png", x: 218, y: 211, size: 35, rot: 0.05 },
      { src: BLUE_KAWAII + "otter-bear.png", x: 29, y: 382, size: 51, rot: -0.08 },
      { src: BLUE_KAWAII + "submarine.png", x: 272, y: 384, size: 58, rot: 0.08 },
      { src: BLUE_KAWAII + "starfish.png", x: 84, y: 381, size: 36, rot: -0.05 },
      { src: BLUE_KAWAII + "star-hug.png", x: 220, y: 381, size: 42, rot: 0.05 },
      { src: BLUE_KAWAII + "shell-bed.png", x: 31, y: 552, size: 60, rot: -0.08 },
      { src: BLUE_KAWAII + "swimming-bear.png", x: 269, y: 554, size: 63, rot: 0.08 },
      { src: BLUE_KAWAII + "coral-nap.png", x: 82, y: 552, size: 50, rot: -0.04 },
      { src: BLUE_KAWAII + "moon-bubble.png", x: 220, y: 552, size: 48, rot: 0.05 },
      { src: BLUE_KAWAII + "coral-shell.png", x: 74, y: 727, size: 76, rot: -0.05 },
      { src: BLUE_KAWAII + "treasure-box.png", x: 228, y: 728, size: 72, rot: 0.05 },
      { src: BLUE_KAWAII + "jellyfish.png", x: 151, y: 732, size: 48, rot: 0 },
    ],
    palette: BLUE_KAWAII_STICKERS,
  },
  {
    id: "butter-kawaii",
    name: "Butter Kawaii",
    cta: "Pick Butter Kawaii 🧺",
    accent: "#d6a84e",
    bg: { type: "grid", color: "#e2bf6b", base: "#fffaf0", cell: 14 },
    panel: { x: 14, y: 34, w: 272, h: 724, r: 4, color: "#f7dfa0", dots: null },
    matColor: "#fffefa",
    photoBorder: "#d8b45b",
    slots: [
      { x: 35, y: 58, w: 230, h: 143 },
      { x: 35, y: 228, w: 230, h: 143 },
      { x: 35, y: 398, w: 230, h: 143 },
      { x: 35, y: 568, w: 230, h: 143 },
    ],
    decorations: [
      { src: YELLOW_KAWAII + "blue-scarf.png", x: 65, y: 47, size: 58, rot: -0.08 },
      { src: YELLOW_KAWAII + "pink-camera.png", x: 238, y: 48, size: 52, rot: 0.08 },
      { src: YELLOW_KAWAII + "green-tree.png", x: 28, y: 132, size: 37, rot: -0.08 },
      { src: YELLOW_KAWAII + "sitting-cat.png", x: 272, y: 135, size: 45, rot: 0.08 },
      { src: YELLOW_KAWAII + "picnic-basket.png", x: 31, y: 211, size: 59, rot: -0.08 },
      { src: YELLOW_KAWAII + "campfire-snack.png", x: 269, y: 213, size: 62, rot: 0.08 },
      { src: YELLOW_KAWAII + "camp-sign.png", x: 85, y: 211, size: 40, rot: -0.04 },
      { src: YELLOW_KAWAII + "pink-cup.png", x: 217, y: 211, size: 40, rot: 0.04 },
      { src: YELLOW_KAWAII + "snack-time.png", x: 29, y: 382, size: 51, rot: -0.08 },
      { src: YELLOW_KAWAII + "flag-cat.png", x: 272, y: 384, size: 54, rot: 0.08 },
      { src: YELLOW_KAWAII + "photo-cards.png", x: 84, y: 381, size: 39, rot: -0.04 },
      { src: YELLOW_KAWAII + "fish-hug.png", x: 220, y: 381, size: 45, rot: 0.05 },
      { src: YELLOW_KAWAII + "tent-camp.png", x: 33, y: 552, size: 65, rot: -0.08 },
      { src: YELLOW_KAWAII + "winter-hug.png", x: 270, y: 554, size: 53, rot: 0.08 },
      { src: YELLOW_KAWAII + "green-tree.png", x: 84, y: 552, size: 38, rot: -0.04 },
      { src: YELLOW_KAWAII + "instrument-cat.png", x: 220, y: 552, size: 48, rot: 0.05 },
      { src: YELLOW_KAWAII + "picnic-basket.png", x: 73, y: 727, size: 70, rot: -0.05 },
      { src: YELLOW_KAWAII + "campfire-snack.png", x: 230, y: 729, size: 72, rot: 0.05 },
      { src: YELLOW_KAWAII + "blue-scarf.png", x: 151, y: 731, size: 50, rot: 0 },
    ],
    palette: YELLOW_KAWAII_STICKERS,
  },
];

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}
